version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: idg
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql

  cache: 
    image: redis
    restart: always
    environment:
      REDIS_PORT_NUMBER: 6379
      REDIS_PASSWORD: 123456
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass 123456
    volumes:
      - ./data/redis:/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
